version: '3'
services:
  redis-server:
    image: 'redis'
  flask-app:
    restart: always
    build: .
    ports:
      - "5000:5000"
      - "6000:6000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock